# Config file in which you should add the sensor heads that you want to connect to and the FoV numbers for those sensor heads.
# Each sensor head can go up to 8 FoVs (i.e. a: [0, 1, 2, 3, 4, 5, 6, 7])
a: [0, 1, 2, 3]
b: [0, 1, 2, 3]
c: [0, 1, 2, 3]
d: [0, 1, 2, 3]
# Position of each sensor head [x, y, z, roll, pitch, yaw]
a_pos: [0., 0., 0., 0., 0., 0.]
b_pos: [-0.1, 0.2, 0., 0., 0., 1.5]
c_pos: [-0.3, 0., 0., 0., 0., 3.0]
d_pos: [-0.1, -0.2, 0., 0., 0., 4.5]
# Visual position of each sensor head [x, y, z, roll, pitch, yaw]
a_vis: [0., 0., 0., 3.1416, 0., 1.5708]
b_vis: [0., 0., 0., 3.1416, 0., 1.5708]
c_vis: [0., 0., 0., 3.1416, 0., 1.5708]
d_vis: [0., 0., 0., 3.1416, 0., 1.5708]